### ISSUE TITLE
Implement loading

### ISSUE THREAD

**Issue by crissm** [IBM/libras-ui#11]
Loading spinners are used when retrieving data or performing slow computations, and help to notify users that loading is underway.

https://react.carbondesignsystem.com/?path=/story/loading--default

![28d5a300-8fba-11ea-8ea5-b218bc31a5f4](https://user-images.githubusercontent.com/33586050/90770390-1a409c80-e2c8-11ea-9a75-89a18aa58fa2.png)

**Comment by asharonbaltazar** [comment]
Can I try implementing this? There's an npm package for React that provides at least a dozen different loading transitions.

Is there a specific way you'd like this function integrated? Perhaps through the `handleClick()`?

**Comment by camilasb** [comment]
we had designed something like this for the transition
-blur
-loading icon

![image](https://user-images.githubusercontent.com/20360162/92662814-0809bb00-f2d6-11ea-96d2-55e0baac0384.png)

can it be done this way?

**Comment by filipecorrea** [comment]
Feito.
