### ISSUE TITLE
Add button to clear text area

### ISSUE THREAD

**Issue by filipecorrea** [IBM/libras-ui#2]
**Is your feature request related to a problem? Please describe.**
As a user, I'm always frustrated that I need to select all text and delete it to start over.

**Describe the solution you'd like**
It would be good to have a way of clearing the text area with a single click:

1. The user inserts text in left text area;
2. The user clicks on 'limpar texto' button;
3. The text area returns to its initial state (without any text in).

**Additional context**

![ec0aab80-8fbb-11ea-9f1e-690a1ef46b26](https://user-images.githubusercontent.com/1496656/90183641-3903d800-dd8a-11ea-8e7a-04415fd7506b.png)

https://ibm.invisionapp.com/d/main?redirHash=#/console/15359913/319489561/preview?scrollOffset=538

**Comment by asharonbaltazar** [comment]
Is this issue still open?

**Comment by filipecorrea** [comment]
Yes, it is.

**Comment by asharonbaltazar** [comment]
Okay, I'll take it. Where would you like the button? Perhaps make the question on the right (sorry, don't speak Spanish) smaller to make room for another button?

**Comment by filipecorrea** [comment]
The button is already on the screen. Please look for `clean-review-Button` (Limpar texto button).

**Comment by asharonbaltazar** [comment]
The button is functioning and deletes text from the textarea.

**Comment by filipecorrea** [comment]
@asharonbaltazar You're right. Someone must have implemented it and I missed that PR.
