### ISSUE TITLE
Text color makes it unreadable

### ISSUE THREAD

**Issue by filipecorrea** [IBM/libras-ui#25]
**Describe the bug**
The color that the text is using makes it unreadable in the right text area.

**To Reproduce**
1. Write any text on the left text area;
2. Click on 'revisar texto' button;
3. See error.

**Expected behavior**
The text should be using the recommended [color theme from Carbon design](https://www.carbondesignsystem.com/guidelines/color/overview#themes). For light themes the text color should be black.

**Screenshots**

![Screen Shot 2020-09-08 at 17 03 07](https://user-images.githubusercontent.com/1496656/92522807-aeca5a80-f1f5-11ea-9003-c86240601d56.png)

![Screen Shot 2020-09-08 at 17 03 23](https://user-images.githubusercontent.com/1496656/92522811-b12cb480-f1f5-11ea-8c0e-cd5f82d98b18.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 85.0.4183.83

**Comment by asharonbaltazar** [comment]
I'll try fixing this! Can I be assigned?
