### ISSUE TITLE
Buttons disappears after clicking

### ISSUE THREAD

**Issue by filipecorrea** [IBM/libras-ui#26]
**Describe the bug**
There's a problem with buttons style that are making them disappear after clicked.

**To Reproduce**
1. Write any text on the left text area;
2. Click on 'revisar texto' button;
3. See error.

**Expected behavior**
After clicked, the buttons should return to its initial state following [Carbon's guidelines](https://react.carbondesignsystem.com/?path=/story/button--default).

**Screenshots**

![Screen Shot 2020-09-08 at 17 03 28](https://user-images.githubusercontent.com/1496656/92523631-1339e980-f1f7-11ea-94d9-d0077eb190b3.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 85.0.4183.83

**Comment by asharonbaltazar** [comment]
Is this issue still open?

**Comment by filipecorrea** [comment]
Hi @asharonbaltazar, thanks for reaching out!

This one is fixed now, but #25 is also a good one to start contributing to this project.
